# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Developer Notes
tagline:             'by Olivier Andriessen'
description:         'Sharing my thoughts and ideas about web development.'
url:                 http://olivierandriessen.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Olivier Andriessen
  url:               http://olivierandriessen.com
  email:             olivierandriessen@gmail.com

# Custom vars
version:             1.0.0

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from