# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["tables"]

highlighter: pygments

# Permalinks
permalink:        pretty

# Setup
title:            Olivier Andriessen
tagline:          'Random articles about web development'
description:      'Sharing random thoughts and ideas about web development.'
url:              http://www.olivierandriessen.com
shorturl:         olivierandriessen.com

author:
  name:           'Olivier Andriessen'
  url:            http://github.com/olivierandriessen
  email:             olivierandriessen@gmail.com

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           github.com/olivierandriessen/olivierandriessen.github.io

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from